apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  annotations:
    github.com/project-slug: POC-CONSENSUS/frontend
spec:
  type: service
  lifecycle: experimental
  owner: group:poc-consensus/awesometeam
  system: naming-convention-generator
